### ISSUE TITLE
数据回测模块，tushare现在好像改了

### ISSUE THREAD

**Issue by sunnychenxx** [AkatsukiYamisora/stock-prediction-with-DL#2]
ts_basic_fields = "trade_date,open,high,low,close,pre_close,vol"
tushare列名现在是这个,股票日线下载用pro.daily，积分要达到120分，由于列名重复，两个表连接时，df1 = df1.join(df2,lsuffix='_l', rsuffix='_r')

**Comment by AkatsukiYamisora** [comment]
对，tushare日线接口之前改过一次，现在用的是新版的【每日指标】api，官网文档：
_每日指标
_接口：daily_basic，可以通过数据工具调试和查看数据。_
_更新时间：交易日每日15点～17点之间_
_描述：获取全部股票每日重要的基本面指标，可用于选股分析、报表展示等。_
_积分：用户需要至少600积分才可以调取，具体请参阅积分获取办法__
因为最开始只用baostock做，所以没有考虑用tushare的daily模块，后来因为baostock没有股本和市值所以还是加上了tushare的部分

**Comment by sunnychenxx** [comment]
> 对，tushare日线接口之前改过一次，现在用的是新版的【每日指标】api，官网文档： _每日指标 _接口：daily_basic，可以通过数据工具调试和查看数据。_ _更新时间：交易日每日15点～17点之间_ _描述：获取全部股票每日重要的基本面指标，可用于选股分析、报表展示等。_ _积分：用户需要至少600积分才可以调取，具体请参阅积分获取办法__ 因为最开始只用baostock做，所以没有考虑用tushare的daily模块，后来因为baostock没有股本和市值所以还是加上了tushare的部分

嗯嗯，我是现在才注册tushare，只有120分，只能用daily,不知道对后面有没有什么影响啊，谢谢作者，刚好是我需要的，非常感谢你，我可以在我的作业用到你的代码吗，我标明出处可以吗，就是课堂作业

**Comment by AkatsukiYamisora** [comment]
可以的可以的^-^

**Comment by AkatsukiYamisora** [comment]
没有积分的话可以直接去掉baostock或者tushare其中一个， 只要把模型的输入去掉没有的输入特征就行，可以参考我旧版本的代码，指标不够的话可以参考我新上传的指标文件

**Comment by sunnychenxx** [comment]
> 

嗯嗯，好的，感恩 : D
